name: people_products
team: people
tier: standard
description: Products pipeline for people
schedule:
  hour: 0
  days: 1-5
steps:
- name: extract
  table: people.raw_products_00
- name: enrich
  table: people.int_products_00
  depends_on:
  - extract
- name: aggregate
  table: people.int_products_00
  depends_on:
  - enrich
  - extract
- name: publish
  table: people.mart_products_00
  depends_on:
  - aggregate
  - enrich
